module(
    name = "active_directory_user_creation_utility",
)

# Hedron's Compile Commands Extractor for Bazel
# https://github.com/hedronvision/bazel-compile-commands-extractor
bazel_dep(name = "hedron_compile_commands", dev_dependency = True)
git_override(
    module_name = "hedron_compile_commands",
    remote = "https://github.com/hedronvision/bazel-compile-commands-extractor.git",
    commit = "4f28899228fb3ad0126897876f147ca15026151e",
    # Replace the commit hash (above) with the latest (https://github.com/hedronvision/bazel-compile-commands-extractor/commits/main).
    # Even better, set up Renovate and let it do the work for you (see "Suggestion: Updates" in the README).
)

bazel_dep(
    name = "tomlplusplus",
    version = "3.4.0",
)

bazel_dep(name = "argparse", version = "3.0.0")
bazel_dep(name = "platforms", version = "0.0.11")
bazel_dep(name = "rules_qt")

git_override(
    module_name = "rules_qt",
    remote = "https://github.com/Vertexwahn/rules_qt6.git",
    commit = "f43d76ab1d3b60bd494e871f4f1042a351bfcff8",
)
qt = use_extension("@rules_qt//:extensions.bzl", "qt")
qt.fetch()
use_repo(
    qt,
    "qt_linux_x86_64",
    "qt_windows_x86_64",
)
register_toolchains(
    "@rules_qt//tools:all",
    dev_dependency = True,
)

bazel_dep(name = "gazelle", version = "0.45.0")
bazel_dep(name = "aspect_rules_lint", version = "1.6.0")

keep_sorted_deps = use_extension("@gazelle//:extensions.bzl", "go_deps", isolate = True)
keep_sorted_deps.from_file(go_mod = "@aspect_rules_lint//lint/keep-sorted:go.mod")
use_repo(keep_sorted_deps, "com_github_google_keep_sorted")
