load("@rules_qt//:qt.bzl", "qt_cc_binary", "qt_cc_library")

# Modules that use Qt:
# addusers <-adprog, addusers, userattrib, userViewGUI
# adprog <-editUsers, addusers, userattrib
# editusers <-adprog, userattrib, userViewGUI
# userViewGUI <-adprog, userattrib

qt_cc_library(
    name = "mess",
    srcs = [
        "old/addusers.cpp",
        "old/adprog.cpp",
        "old/editusers.cpp",
        "old/userViewGUI.cpp",
    ],
    hdrs = [
        "old/addusers.h",
        "old/adprog.h",
        "old/editUsers.h",
        "old/userViewGUI.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":userattrib",
        "@rules_qt//:qt_core",
        "@rules_qt//:qt_gui",
        "@rules_qt//:qt_widgets",
    ],
)

# Pure C:
# helperfuncs
# userattrib

cc_library(
    name = "userattrib",
    srcs = ["old/userattrib.c"],
    hdrs = ["old/userattrib.h"],
    visibility = ["//visibility:public"],
    deps = [":helperfuncs"],
)

cc_library(
    name = "helperfuncs",
    srcs = ["old/helperfuncs.c"],
    hdrs = ["old/helperfuncs.h"],
    visibility = ["//visibility:public"],
)

qt_cc_binary(
    name = "ADProg",
    srcs = ["old/main.cpp"],
    data = ["settings.dat"],
    visibility = ["//visibility:public"],
    deps = [
        ":mess",
        "@rules_qt//:qt_core",
        "@rules_qt//:qt_widgets",
    ],
)
